name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Build zip
        run: |
          MODULE=moonewsmancoupon
          mkdir -p dist
          zip -r "dist/${MODULE}.zip" "${MODULE}" -x "${MODULE}/.git/**" "${MODULE}/dist/**"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/moonewsmancoupon.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
